In [1]:
import numpy as np
data = np.array([1,2,3])
print(data)


[1 2 3]


In [2]:
data.max()

3

In [3]:
np.ones(3)

array([1., 1., 1.])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.random.random(3)

array([0.08847003, 0.87021223, 0.35271568])

In [6]:
data1 = np.array([1,2])
ones = np.ones(2)
data1 + ones

array([2., 3.])

In [7]:
data1 - ones

array([0., 1.])

In [8]:
data1 * data1

array([1, 4])

In [9]:
data1 / data1

array([1., 1.])

In [10]:
data1 * 1.6

array([1.6, 3.2])

In [11]:
data[0]

1

In [12]:
data[1]

2

In [13]:
data[0:2]

array([1, 2])

In [14]:
data[1:]

array([2, 3])

In [15]:
data.max()

3

In [16]:
data.min()

1

In [17]:
data.sum()

6

In [18]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [19]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
np.random.random((3,2))

array([[0.46449382, 0.2268965 ],
       [0.16818857, 0.78749177],
       [0.55865456, 0.00459978]])

In [21]:
np.ones(2)
data = ([1,2],[3,4],[5,6])
data + ones

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [22]:
data = ([1,2,3])
powers_of_ten = ([1,10],[100,1000],[10000,100000])
np.dot(data,powers_of_ten)

array([ 30201, 302010])

In [23]:
data = np.array([[1,2],[3,4],[5,6]])
data[0,1]

2

In [24]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [25]:
data[0:2,0]

array([1, 3])

In [26]:
data.max(axis=0)

array([5, 6])

In [27]:
data.max(axis = 1)

array([2, 4, 6])

In [28]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [29]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
data2 = np.array([[[1,2],[3,4],[5,6],[7,8]]])
data2

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [32]:
c = np.arange(1,13).reshape(6,2)
c

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [33]:
np.vsplit(c,3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [34]:
d = c.T
d

array([[ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [35]:
np.hsplit(d,3)

[array([[1, 3],
        [2, 4]]),
 array([[5, 7],
        [6, 8]]),
 array([[ 9, 11],
        [10, 12]])]

In [36]:
a = ([11,12,13],[14,15,16],[17,18,19])
b = ([21,22,23],[24,25,26],[27,28,29])
e =  np.dstack((a,b))
e

array([[[11, 21],
        [12, 22],
        [13, 23]],

       [[14, 24],
        [15, 25],
        [16, 26]],

       [[17, 27],
        [18, 28],
        [19, 29]]])

In [37]:
np.dsplit(e,2)

[array([[[11],
         [12],
         [13]],
 
        [[14],
         [15],
         [16]],
 
        [[17],
         [18],
         [19]]]),
 array([[[21],
         [22],
         [23]],
 
        [[24],
         [25],
         [26]],
 
        [[27],
         [28],
         [29]]])]

In [38]:
inistate = np.array([1,2,3,4])
pre_inistate = inistate[0:3]
pre_inistate

array([1, 2, 3])

In [39]:
a = np.array([1,1,1,1])
b = np.array([[1],[1],[1],[1]])
a+b

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [40]:
c = np.array([[1,1,1,1]])
c+b

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [41]:
W = np.array([[1,1,1],[2,2,2]])
W[:,1]

array([1, 2])

In [42]:
W[1]

array([2, 2, 2])

In [43]:
W[:,1] = np.array([5,5])
W

array([[1, 5, 1],
       [2, 5, 2]])

In [44]:
matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [45]:
p1 = np.delete(matrix,1,0)
p1

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [46]:
p2 = np.delete(matrix,1,1)
p2

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [47]:
p3 = np.delete(matrix,1)
p3

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
p4 = np.delete(matrix,[0,1],1)
p4

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [49]:
matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
matrix

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [50]:
q1 = np.insert(matrix,1,[1,1,1,1],0)
q1

array([[ 1,  2,  3,  4],
       [ 1,  1,  1,  1],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
q2 = np.insert(matrix,0,[1,1,1],1)
q2

array([[ 1,  1,  2,  3,  4],
       [ 1,  5,  6,  7,  8],
       [ 1,  9, 10, 11, 12]])

In [52]:
q3 = np.insert(matrix,3,[1,1,1,1],0)
q3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [53]:
matrix = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
m1 = np.append(matrix,[[1,1,1,1]],0)
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

In [54]:
m2 = np.append(matrix,[[1],[1],[1]],1)
m2

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  1],
       [ 9, 10, 11, 12,  1]])

In [55]:
m3 = np.append(matrix,[1,1,1,1])
m3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,  1,  1,  1,  1])

In [56]:
a1 = np.random.choice(7,5)
a1

array([5, 3, 1, 0, 4])

In [57]:
a2 = np.random.choice([0,1,2,3,4,5,6],5)
a2

array([5, 4, 0, 6, 4])

In [58]:
a3 = np.random.choice(np.array([0,1,2,3,4,5,6]),5)
a3

array([2, 2, 4, 5, 1])

In [59]:
a4 = np.random.choice([0,1,2,3,4,5,6],5,False)
a4

array([1, 5, 2, 4, 3])

In [60]:
a5 = np.random.choice(np.array([0,1,2,3,4,5,6]),5,p=[0.1,0.1,0.1,0.1,0.2,0.1,0.3])
a5

array([1, 4, 4, 0, 4])

In [61]:
a = np.array([[1,1,1],[2,2,2],[0,3,6]])
a

array([[1, 1, 1],
       [2, 2, 2],
       [0, 3, 6]])

In [62]:
b1 = np.argmax(a)
b1

8

In [63]:
b2 = np.argmax(a,0)
b2

array([1, 2, 2], dtype=int64)

In [64]:
b3 = np.argmax(a,1)
b3

array([0, 0, 2], dtype=int64)

In [65]:
y1 = np.linspace(-10.0,10.0)
y1

array([-10.        ,  -9.59183673,  -9.18367347,  -8.7755102 ,
        -8.36734694,  -7.95918367,  -7.55102041,  -7.14285714,
        -6.73469388,  -6.32653061,  -5.91836735,  -5.51020408,
        -5.10204082,  -4.69387755,  -4.28571429,  -3.87755102,
        -3.46938776,  -3.06122449,  -2.65306122,  -2.24489796,
        -1.83673469,  -1.42857143,  -1.02040816,  -0.6122449 ,
        -0.20408163,   0.20408163,   0.6122449 ,   1.02040816,
         1.42857143,   1.83673469,   2.24489796,   2.65306122,
         3.06122449,   3.46938776,   3.87755102,   4.28571429,
         4.69387755,   5.10204082,   5.51020408,   5.91836735,
         6.32653061,   6.73469388,   7.14285714,   7.55102041,
         7.95918367,   8.36734694,   8.7755102 ,   9.18367347,
         9.59183673,  10.        ])

In [66]:
y2 = np.linspace(1,10,10)
y2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [67]:
y3 = np.linspace(1,10,10,False)
y3

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [68]:
y4 = np.linspace(1,10,6,True)
y4

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. ])

In [69]:
x = np.array([[1,2,3],[4,5,6],[1,2,3]])
x.flatten()

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [70]:
x.ravel()

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [71]:
x.ravel('F')

array([1, 4, 1, 2, 5, 2, 3, 6, 3])

In [72]:
x.flatten()[1] = 20
x

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [73]:
x.ravel()[2] = 20
x

array([[ 1,  2, 20],
       [ 4,  5,  6],
       [ 1,  2,  3]])

In [74]:
x.reshape(1,-1)

array([[ 1,  2, 20,  4,  5,  6,  1,  2,  3]])

In [75]:
x = np.array([1,2,3,4,5,6,7,8])
x[None,:]

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [76]:
x[:,None]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [77]:
x[np.newaxis,:]

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [78]:
x = np.array([[1,2,3],[2,3,4]])
np.prod(x)

144

In [79]:
np.prod(x,axis=1)

array([ 6, 24])

In [80]:
np.prod(x,axis=0)

array([ 2,  6, 12])

In [81]:
x = np.array([[1,2,3],[-3,2,4],[5,-2,9]])
x

array([[ 1,  2,  3],
       [-3,  2,  4],
       [ 5, -2,  9]])

In [82]:
y1 = np.maximum(0,x)
y1

array([[1, 2, 3],
       [0, 2, 4],
       [5, 0, 9]])

In [83]:
y2 = np.minimum(0,x)
y2

array([[ 0,  0,  0],
       [-3,  0,  0],
       [ 0, -2,  0]])

In [94]:
x1 = x.copy()
x1

array([[ 1,  2,  3],
       [-3,  2,  4],
       [ 5, -2,  9]])

In [95]:
x1[x1 < 0] = 0 
x1

array([[1, 2, 3],
       [0, 2, 4],
       [5, 0, 9]])

In [96]:
x2 = x.copy()
x2[x2 > 0] = 0
x2

array([[ 0,  0,  0],
       [-3,  0,  0],
       [ 0, -2,  0]])

In [97]:
x = np.array([[1,2,3],[-3,2,4],[5,-2,9]])
x

array([[ 1,  2,  3],
       [-3,  2,  4],
       [ 5, -2,  9]])

In [98]:
x1 = x.copy()
x1[x1>0] = 0
x1

array([[ 0,  0,  0],
       [-3,  0,  0],
       [ 0, -2,  0]])

In [99]:
x

array([[ 1,  2,  3],
       [-3,  2,  4],
       [ 5, -2,  9]])

In [100]:
x2 = x
x2

array([[ 1,  2,  3],
       [-3,  2,  4],
       [ 5, -2,  9]])

In [101]:
x2[x2>0] = 0
x2

array([[ 0,  0,  0],
       [-3,  0,  0],
       [ 0, -2,  0]])

In [102]:
x

array([[ 0,  0,  0],
       [-3,  0,  0],
       [ 0, -2,  0]])

In [103]:
x =  np.array([[1,2,3],[-3,2,4],[5,-2,9]])
x3 =x[2]
x3

array([ 5, -2,  9])

In [104]:
x3[2]=100
x

array([[  1,   2,   3],
       [ -3,   2,   4],
       [  5,  -2, 100]])

In [105]:
x = np.array([[1,2,3],[4,5,6]])
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

In [106]:
np.random.random()

0.2509486470313159

In [107]:
np.random.uniform()

0.16116546818846367

In [109]:
np.random.rand(3,4)

array([[0.26848859, 0.75677135, 0.14552737, 0.26261256],
       [0.54780844, 0.67402059, 0.62436472, 0.00488821],
       [0.93415865, 0.46570559, 0.8714277 , 0.63993777]])

In [110]:
np.random.randn(2,3)

array([[-0.03041656,  0.26256407, -0.24096193],
       [-1.2218074 ,  0.5473061 , -0.3897216 ]])

In [112]:
y = np.multiply(0.1,np.random.randn(2,3))+0.5
y

array([[0.47155687, 0.31142985, 0.56419872],
       [0.50471705, 0.39481605, 0.39906778]])

In [113]:
np.random.randint(2,9,(2,3))

array([[3, 3, 4],
       [3, 5, 8]])

In [119]:
np.random.randint(9,size = (2,3))

array([[1, 0, 5],
       [1, 0, 7]])

In [125]:
x = 'You are right'
type(x)

str

In [126]:
assert type(x) == str,'x is not str'
x = [1,2,3]
type(x)

list

In [127]:
a = np.arange(95,99).reshape(2,2)
a

array([[95, 96],
       [97, 98]])

In [128]:
np.pad(a,((3,2),(2,3)),'constant',constant_values = (0,0))

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 95, 96,  0,  0,  0],
       [ 0,  0, 97, 98,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [129]:
b = np.array([[[1,2],[3,4]],[[3,4],[7,8]],[[4,5],[1,2]]])
b

array([[[1, 2],
        [3, 4]],

       [[3, 4],
        [7, 8]],

       [[4, 5],
        [1, 2]]])

In [131]:
np.pad(b,((0,0),(1,1),(1,1)),'constant',constant_values = 0)

array([[[0, 0, 0, 0],
        [0, 1, 2, 0],
        [0, 3, 4, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 3, 4, 0],
        [0, 7, 8, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 4, 5, 0],
        [0, 1, 2, 0],
        [0, 0, 0, 0]]])

In [134]:
x = np.empty([3,2],dtype = int)
x

array([[-654719872,        398],
       [         0,          0],
       [    131074,         46]])

In [139]:
a = np.array([[1,2,3],[1,2,3]])
b = np.array([[1,2,3],[1,2,3]])
c = np.array([[1,4,3],[1,2,3]])
(a==b).all()

True

In [140]:
(a==c).all()

False

In [141]:
(a==c).any()

True

In [142]:
c = np.array([[1,2],[3,4]])
c

array([[1, 2],
       [3, 4]])

In [143]:
c.astype(np.float32)


array([[1., 2.],
       [3., 4.]], dtype=float32)

In [146]:
x= np.array([1,3,5])
y = np.array([4,6])
XX,YY=np.meshgrid(x,y)
XX

array([[1, 3, 5],
       [1, 3, 5]])

In [147]:
YY

array([[4, 4, 4],
       [6, 6, 6]])

In [148]:
a = np.array([0.125,0.568,5.688])
np.round(a)

array([0., 1., 6.])

In [149]:
np.round(a,decimals=2)

array([0.12, 0.57, 5.69])

In [150]:
np.floor(a)

array([0., 0., 5.])

In [151]:
np.ceil(a)

array([1., 1., 6.])

In [152]:
c = np.array([1,2,5,4])
c[:,np.newaxis]

array([[1],
       [2],
       [5],
       [4]])

In [153]:
c[np.newaxis,:]

array([[1, 2, 5, 4]])

In [154]:
a = np.array([[1,2,3],[4,5,6]])
a = np.array([[1,2,3,6],[4,5,6,6]])
a1 = a.reshape((1,2,4))
a1

array([[[1, 2, 3, 6],
        [4, 5, 6, 6]]])

In [155]:
b = np.array([[3,4,5,6],[1,2,3,4],[4,5,5,5]])
b

array([[3, 4, 5, 6],
       [1, 2, 3, 4],
       [4, 5, 5, 5]])

In [156]:
b1 = b.reshape((1,3,4)).transpose((1,0,2))
b1

array([[[3, 4, 5, 6]],

       [[1, 2, 3, 4]],

       [[4, 5, 5, 5]]])

In [157]:
a1+b1

array([[[ 4,  6,  8, 12],
        [ 7,  9, 11, 12]],

       [[ 2,  4,  6, 10],
        [ 5,  7,  9, 10]],

       [[ 5,  7,  8, 11],
        [ 8, 10, 11, 11]]])

In [158]:
c = np.array([[[1,2,5],[3,4,6]],[[4,5,6],[7,8,9]]])
c.transpose(1,0,2)

array([[[1, 2, 5],
        [4, 5, 6]],

       [[3, 4, 6],
        [7, 8, 9]]])

In [159]:
a = np.array([2,2,3,4,5,5,6,7])
a[0:7:2]

array([2, 3, 5, 6])

In [160]:
a = np.array([2,2,3,4,5,5,6,7])
a[0::2]

array([2, 3, 5, 6])